# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Custom ZSH config with ohmyzsh plugin
#
# Load oh-my-zsh
export ZSH=$HOME/.oh-my-zsh
#
# Load theme
ZSH_THEME="powerlevel10k/powerlevel10k"
#
# Enable some plugins
plugins=(git zsh-syntax-highlighting docker zsh-kubectl-prompt zsh-autosuggestions)
#
# Disable auto update use $> omz update
DISABLE_AUTO_UPDATE="true"
#
# Setup golang path
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/go/bin
export PATH=$PATH:/opt/homebrew/bin
#
# Load custom config
source $ZSH/oh-my-zsh.sh
source $HOME/perso/01-GIT/dotfiles/shell/my_alias.sh
#
# Load Rust
# source $HOME/.cargo/env
#
# Show kubernetes context
RPROMPT='%{$fg[blue]%}($ZSH_KUBECTL_PROMPT)%{$reset_color%}'
export USE_GKE_GCLOUD_AUTH_PLUGIN=True
# Load Gcloud
source "$(brew --prefix)/share/google-cloud-sdk/path.zsh.inc"
source "$(brew --prefix)/share/google-cloud-sdk/completion.zsh.inc"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
