# Custom ZSH config with ohmyzsh plugin
#
# Load oh-my-zsh
export ZSH=$HOME/.oh-my-zsh
#
# Load theme
ZSH_THEME="risto"
#
# Enable some plugins
plugins=(git zsh-syntax-highlighting docker zsh-kubectl-prompt)
#
# Disable auto update use $> omz update
DISABLE_AUTO_UPDATE="true"
#
# Setup golang path
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/go/bin
export PATH=$PATH:/home/remi/.local/bin
#
# Load custom config
source $ZSH/oh-my-zsh.sh
source $HOME/perso/01-GIT/dotfiles/shell/my_alias.sh
#
# Load Rust
source $HOME/.cargo/env
# Docker socket
export DOCKER_HOST=unix:///run/user/1000/docker.sock
#
# Show kubernetes context
RPROMPT='%{$fg[blue]%}($ZSH_KUBECTL_PROMPT)%{$reset_color%}'
# Load GCP
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/remi/google-cloud-sdk/path.zsh.inc' ]; then . '/home/remi/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/remi/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/remi/google-cloud-sdk/completion.zsh.inc'; fi
