# Custom ZSH config with ohmyzsh plugin
#
# Load oh-my-zsh
export ZSH=$HOME/.oh-my-zsh
#
# Load theme
fpath+=$HOME/00-CONFIG/config/shell/pure
ZSH_THEME="pure"
#
# Enable some plugins
plugins=(git zsh-syntax-highlighting docker zsh-kubectl-prompt)
#
# Disable auto update use $> omz update
DISABLE_AUTO_UPDATE="true"
#
# Setup golang path
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/go/bin
#
# Load custom config
source $ZSH/oh-my-zsh.sh
source $HOME/00-CONFIG/config/shell/my_alias.sh
#
# Load Rust
source $HOME/.cargo/env
#
# Show kubernetes context
RPROMPT='%{$fg[blue]%}($ZSH_KUBECTL_PROMPT)%{$reset_color%}'
